### ISSUE TITLE
Homepage: Beefier buttons

### ISSUE THREAD

**Issue by mcmullengreg** [XavierUniversity/v5-playground#10]
Increase the height (with padding) to be at/around 86px. Add 10px top and bottom.

**Comment by lwhitaker** [comment]
is this for featured links? a little confused on increasing the height with padding and then adding a top and bottom of 10px.

**Comment by mcmullengreg** [comment]
You only need to add the padding. It should be `10px` more on both sides (top/bottom) than what you have now.

**Comment by lwhitaker** [comment]
cool. think we're good here.
