### ISSUE TITLE
Homepage: Remove all fixed widths

### ISSUE THREAD

**Issue by mcmullengreg** [XavierUniversity/v5-playground#9]
Remove the fixed widths and allow for the margin/padding to take control of the edge limits.

This includes the Modules and the Buttons on the homepage.

**Comment by lwhitaker** [comment]
Do I need to remove the widths altogether? Do they just not need to be defined?

**Comment by mcmullengreg** [comment]
`.wrapper` would provide the padding needed across the board and should be used instead of any fixed or defined widths.

**Comment by lwhitaker** [comment]
specifically for the grid, i got rid of the width and did as you suggested in letting the margins and padding do it's thing. will send in then next push. also didn't see anything else on the homepage with a fixed with so i think we're good.

**Comment by mcmullengreg** [comment]
Did you put a width or anything on the buttons? I know you said something about not taking them as far out as the footer buttons.

**Comment by lwhitaker** [comment]
inside the unordered list, the `li` bullets are using `footer__nav-item` and that has a width. it's from the `__footer.scss`. you want me to take those out?
